// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/test.proto

package protobuf.api;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TestResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.api.TestResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 prop1 = 1;</code>
     */
    boolean hasProp1();
    /**
     * <code>required int32 prop1 = 1;</code>
     */
    int getProp1();

    /**
     * <code>required string prop2 = 2;</code>
     */
    boolean hasProp2();
    /**
     * <code>required string prop2 = 2;</code>
     */
    java.lang.String getProp2();
    /**
     * <code>required string prop2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getProp2Bytes();

    /**
     * <code>required int64 prop3 = 3;</code>
     */
    boolean hasProp3();
    /**
     * <code>required int64 prop3 = 3;</code>
     */
    long getProp3();

    /**
     * <code>repeated string prop4 = 4;</code>
     */
    com.google.protobuf.ProtocolStringList
        getProp4List();
    /**
     * <code>repeated string prop4 = 4;</code>
     */
    int getProp4Count();
    /**
     * <code>repeated string prop4 = 4;</code>
     */
    java.lang.String getProp4(int index);
    /**
     * <code>repeated string prop4 = 4;</code>
     */
    com.google.protobuf.ByteString
        getProp4Bytes(int index);
  }
  /**
   * Protobuf type {@code protobuf.api.TestResponse}
   */
  public static final class TestResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.api.TestResponse)
      TestResponseOrBuilder {
    // Use TestResponse.newBuilder() to construct.
    private TestResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestResponse defaultInstance;
    public static TestResponse getDefaultInstance() {
      return defaultInstance;
    }

    public TestResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              prop1_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              prop2_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              prop3_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                prop4_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              prop4_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          prop4_ = prop4_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.api.Test.internal_static_protobuf_api_TestResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.api.Test.internal_static_protobuf_api_TestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.api.Test.TestResponse.class, protobuf.api.Test.TestResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<TestResponse> PARSER =
        new com.google.protobuf.AbstractParser<TestResponse>() {
      public TestResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PROP1_FIELD_NUMBER = 1;
    private int prop1_;
    /**
     * <code>required int32 prop1 = 1;</code>
     */
    public boolean hasProp1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 prop1 = 1;</code>
     */
    public int getProp1() {
      return prop1_;
    }

    public static final int PROP2_FIELD_NUMBER = 2;
    private java.lang.Object prop2_;
    /**
     * <code>required string prop2 = 2;</code>
     */
    public boolean hasProp2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string prop2 = 2;</code>
     */
    public java.lang.String getProp2() {
      java.lang.Object ref = prop2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          prop2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string prop2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProp2Bytes() {
      java.lang.Object ref = prop2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prop2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROP3_FIELD_NUMBER = 3;
    private long prop3_;
    /**
     * <code>required int64 prop3 = 3;</code>
     */
    public boolean hasProp3() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 prop3 = 3;</code>
     */
    public long getProp3() {
      return prop3_;
    }

    public static final int PROP4_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList prop4_;
    /**
     * <code>repeated string prop4 = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getProp4List() {
      return prop4_;
    }
    /**
     * <code>repeated string prop4 = 4;</code>
     */
    public int getProp4Count() {
      return prop4_.size();
    }
    /**
     * <code>repeated string prop4 = 4;</code>
     */
    public java.lang.String getProp4(int index) {
      return prop4_.get(index);
    }
    /**
     * <code>repeated string prop4 = 4;</code>
     */
    public com.google.protobuf.ByteString
        getProp4Bytes(int index) {
      return prop4_.getByteString(index);
    }

    private void initFields() {
      prop1_ = 0;
      prop2_ = "";
      prop3_ = 0L;
      prop4_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProp1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProp2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProp3()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, prop1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getProp2Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, prop3_);
      }
      for (int i = 0; i < prop4_.size(); i++) {
        output.writeBytes(4, prop4_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, prop1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getProp2Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, prop3_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < prop4_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(prop4_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getProp4List().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.api.Test.TestResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.Test.TestResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.Test.TestResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.Test.TestResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.Test.TestResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.Test.TestResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.api.Test.TestResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.api.Test.TestResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.api.Test.TestResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.Test.TestResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.api.Test.TestResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.api.TestResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.api.TestResponse)
        protobuf.api.Test.TestResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.api.Test.internal_static_protobuf_api_TestResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.api.Test.internal_static_protobuf_api_TestResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.api.Test.TestResponse.class, protobuf.api.Test.TestResponse.Builder.class);
      }

      // Construct using protobuf.api.Test.TestResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        prop1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        prop2_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        prop3_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        prop4_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.api.Test.internal_static_protobuf_api_TestResponse_descriptor;
      }

      public protobuf.api.Test.TestResponse getDefaultInstanceForType() {
        return protobuf.api.Test.TestResponse.getDefaultInstance();
      }

      public protobuf.api.Test.TestResponse build() {
        protobuf.api.Test.TestResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.api.Test.TestResponse buildPartial() {
        protobuf.api.Test.TestResponse result = new protobuf.api.Test.TestResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.prop1_ = prop1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.prop2_ = prop2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.prop3_ = prop3_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          prop4_ = prop4_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.prop4_ = prop4_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.api.Test.TestResponse) {
          return mergeFrom((protobuf.api.Test.TestResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.api.Test.TestResponse other) {
        if (other == protobuf.api.Test.TestResponse.getDefaultInstance()) return this;
        if (other.hasProp1()) {
          setProp1(other.getProp1());
        }
        if (other.hasProp2()) {
          bitField0_ |= 0x00000002;
          prop2_ = other.prop2_;
          onChanged();
        }
        if (other.hasProp3()) {
          setProp3(other.getProp3());
        }
        if (!other.prop4_.isEmpty()) {
          if (prop4_.isEmpty()) {
            prop4_ = other.prop4_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureProp4IsMutable();
            prop4_.addAll(other.prop4_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasProp1()) {
          
          return false;
        }
        if (!hasProp2()) {
          
          return false;
        }
        if (!hasProp3()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.api.Test.TestResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.api.Test.TestResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int prop1_ ;
      /**
       * <code>required int32 prop1 = 1;</code>
       */
      public boolean hasProp1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 prop1 = 1;</code>
       */
      public int getProp1() {
        return prop1_;
      }
      /**
       * <code>required int32 prop1 = 1;</code>
       */
      public Builder setProp1(int value) {
        bitField0_ |= 0x00000001;
        prop1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 prop1 = 1;</code>
       */
      public Builder clearProp1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        prop1_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object prop2_ = "";
      /**
       * <code>required string prop2 = 2;</code>
       */
      public boolean hasProp2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string prop2 = 2;</code>
       */
      public java.lang.String getProp2() {
        java.lang.Object ref = prop2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            prop2_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string prop2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProp2Bytes() {
        java.lang.Object ref = prop2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          prop2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string prop2 = 2;</code>
       */
      public Builder setProp2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        prop2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string prop2 = 2;</code>
       */
      public Builder clearProp2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        prop2_ = getDefaultInstance().getProp2();
        onChanged();
        return this;
      }
      /**
       * <code>required string prop2 = 2;</code>
       */
      public Builder setProp2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        prop2_ = value;
        onChanged();
        return this;
      }

      private long prop3_ ;
      /**
       * <code>required int64 prop3 = 3;</code>
       */
      public boolean hasProp3() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 prop3 = 3;</code>
       */
      public long getProp3() {
        return prop3_;
      }
      /**
       * <code>required int64 prop3 = 3;</code>
       */
      public Builder setProp3(long value) {
        bitField0_ |= 0x00000004;
        prop3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 prop3 = 3;</code>
       */
      public Builder clearProp3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        prop3_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList prop4_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureProp4IsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          prop4_ = new com.google.protobuf.LazyStringArrayList(prop4_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string prop4 = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getProp4List() {
        return prop4_.getUnmodifiableView();
      }
      /**
       * <code>repeated string prop4 = 4;</code>
       */
      public int getProp4Count() {
        return prop4_.size();
      }
      /**
       * <code>repeated string prop4 = 4;</code>
       */
      public java.lang.String getProp4(int index) {
        return prop4_.get(index);
      }
      /**
       * <code>repeated string prop4 = 4;</code>
       */
      public com.google.protobuf.ByteString
          getProp4Bytes(int index) {
        return prop4_.getByteString(index);
      }
      /**
       * <code>repeated string prop4 = 4;</code>
       */
      public Builder setProp4(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProp4IsMutable();
        prop4_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string prop4 = 4;</code>
       */
      public Builder addProp4(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProp4IsMutable();
        prop4_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string prop4 = 4;</code>
       */
      public Builder addAllProp4(
          java.lang.Iterable<java.lang.String> values) {
        ensureProp4IsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, prop4_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string prop4 = 4;</code>
       */
      public Builder clearProp4() {
        prop4_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string prop4 = 4;</code>
       */
      public Builder addProp4Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProp4IsMutable();
        prop4_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.api.TestResponse)
    }

    static {
      defaultInstance = new TestResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.api.TestResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_api_TestResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_api_TestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016api/test.proto\022\014protobuf.api\032\021schema/u" +
      "ser.proto\"J\n\014TestResponse\022\r\n\005prop1\030\001 \002(\005" +
      "\022\r\n\005prop2\030\002 \002(\t\022\r\n\005prop3\030\003 \002(\003\022\r\n\005prop4\030" +
      "\004 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protobuf.schema.UserOuterClass.getDescriptor(),
        }, assigner);
    internal_static_protobuf_api_TestResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_api_TestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_api_TestResponse_descriptor,
        new java.lang.String[] { "Prop1", "Prop2", "Prop3", "Prop4", });
    protobuf.schema.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
