// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/test.proto

package protobuf.api;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TestResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.api.TestResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required .protobuf.schema.User user1 = 4;</code>
     */
    boolean hasUser1();
    /**
     * <code>required .protobuf.schema.User user1 = 4;</code>
     */
    protobuf.schema.UserOuterClass.User getUser1();
    /**
     * <code>required .protobuf.schema.User user1 = 4;</code>
     */
    protobuf.schema.UserOuterClass.UserOrBuilder getUser1OrBuilder();

    /**
     * <code>required .protobuf.schema.User user2 = 8;</code>
     */
    boolean hasUser2();
    /**
     * <code>required .protobuf.schema.User user2 = 8;</code>
     */
    protobuf.schema.UserOuterClass.User getUser2();
    /**
     * <code>required .protobuf.schema.User user2 = 8;</code>
     */
    protobuf.schema.UserOuterClass.UserOrBuilder getUser2OrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.api.TestResponse}
   */
  public static final class TestResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.api.TestResponse)
      TestResponseOrBuilder {
    // Use TestResponse.newBuilder() to construct.
    private TestResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestResponse defaultInstance;
    public static TestResponse getDefaultInstance() {
      return defaultInstance;
    }

    public TestResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 34: {
              protobuf.schema.UserOuterClass.User.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = user1_.toBuilder();
              }
              user1_ = input.readMessage(protobuf.schema.UserOuterClass.User.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user1_);
                user1_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 66: {
              protobuf.schema.UserOuterClass.User.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = user2_.toBuilder();
              }
              user2_ = input.readMessage(protobuf.schema.UserOuterClass.User.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user2_);
                user2_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.api.Test.internal_static_protobuf_api_TestResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.api.Test.internal_static_protobuf_api_TestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.api.Test.TestResponse.class, protobuf.api.Test.TestResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<TestResponse> PARSER =
        new com.google.protobuf.AbstractParser<TestResponse>() {
      public TestResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int USER1_FIELD_NUMBER = 4;
    private protobuf.schema.UserOuterClass.User user1_;
    /**
     * <code>required .protobuf.schema.User user1 = 4;</code>
     */
    public boolean hasUser1() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .protobuf.schema.User user1 = 4;</code>
     */
    public protobuf.schema.UserOuterClass.User getUser1() {
      return user1_;
    }
    /**
     * <code>required .protobuf.schema.User user1 = 4;</code>
     */
    public protobuf.schema.UserOuterClass.UserOrBuilder getUser1OrBuilder() {
      return user1_;
    }

    public static final int USER2_FIELD_NUMBER = 8;
    private protobuf.schema.UserOuterClass.User user2_;
    /**
     * <code>required .protobuf.schema.User user2 = 8;</code>
     */
    public boolean hasUser2() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .protobuf.schema.User user2 = 8;</code>
     */
    public protobuf.schema.UserOuterClass.User getUser2() {
      return user2_;
    }
    /**
     * <code>required .protobuf.schema.User user2 = 8;</code>
     */
    public protobuf.schema.UserOuterClass.UserOrBuilder getUser2OrBuilder() {
      return user2_;
    }

    private void initFields() {
      id_ = 0;
      user1_ = protobuf.schema.UserOuterClass.User.getDefaultInstance();
      user2_ = protobuf.schema.UserOuterClass.User.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUser1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUser2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUser1().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUser2().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(4, user1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(8, user2_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, user1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, user2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.api.Test.TestResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.Test.TestResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.Test.TestResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.Test.TestResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.Test.TestResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.Test.TestResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.api.Test.TestResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.api.Test.TestResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.api.Test.TestResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.Test.TestResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.api.Test.TestResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.api.TestResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.api.TestResponse)
        protobuf.api.Test.TestResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.api.Test.internal_static_protobuf_api_TestResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.api.Test.internal_static_protobuf_api_TestResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.api.Test.TestResponse.class, protobuf.api.Test.TestResponse.Builder.class);
      }

      // Construct using protobuf.api.Test.TestResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUser1FieldBuilder();
          getUser2FieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (user1Builder_ == null) {
          user1_ = protobuf.schema.UserOuterClass.User.getDefaultInstance();
        } else {
          user1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (user2Builder_ == null) {
          user2_ = protobuf.schema.UserOuterClass.User.getDefaultInstance();
        } else {
          user2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.api.Test.internal_static_protobuf_api_TestResponse_descriptor;
      }

      public protobuf.api.Test.TestResponse getDefaultInstanceForType() {
        return protobuf.api.Test.TestResponse.getDefaultInstance();
      }

      public protobuf.api.Test.TestResponse build() {
        protobuf.api.Test.TestResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.api.Test.TestResponse buildPartial() {
        protobuf.api.Test.TestResponse result = new protobuf.api.Test.TestResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (user1Builder_ == null) {
          result.user1_ = user1_;
        } else {
          result.user1_ = user1Builder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (user2Builder_ == null) {
          result.user2_ = user2_;
        } else {
          result.user2_ = user2Builder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.api.Test.TestResponse) {
          return mergeFrom((protobuf.api.Test.TestResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.api.Test.TestResponse other) {
        if (other == protobuf.api.Test.TestResponse.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUser1()) {
          mergeUser1(other.getUser1());
        }
        if (other.hasUser2()) {
          mergeUser2(other.getUser2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasUser1()) {
          
          return false;
        }
        if (!hasUser2()) {
          
          return false;
        }
        if (!getUser1().isInitialized()) {
          
          return false;
        }
        if (!getUser2().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.api.Test.TestResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.api.Test.TestResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private protobuf.schema.UserOuterClass.User user1_ = protobuf.schema.UserOuterClass.User.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protobuf.schema.UserOuterClass.User, protobuf.schema.UserOuterClass.User.Builder, protobuf.schema.UserOuterClass.UserOrBuilder> user1Builder_;
      /**
       * <code>required .protobuf.schema.User user1 = 4;</code>
       */
      public boolean hasUser1() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .protobuf.schema.User user1 = 4;</code>
       */
      public protobuf.schema.UserOuterClass.User getUser1() {
        if (user1Builder_ == null) {
          return user1_;
        } else {
          return user1Builder_.getMessage();
        }
      }
      /**
       * <code>required .protobuf.schema.User user1 = 4;</code>
       */
      public Builder setUser1(protobuf.schema.UserOuterClass.User value) {
        if (user1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user1_ = value;
          onChanged();
        } else {
          user1Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.schema.User user1 = 4;</code>
       */
      public Builder setUser1(
          protobuf.schema.UserOuterClass.User.Builder builderForValue) {
        if (user1Builder_ == null) {
          user1_ = builderForValue.build();
          onChanged();
        } else {
          user1Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.schema.User user1 = 4;</code>
       */
      public Builder mergeUser1(protobuf.schema.UserOuterClass.User value) {
        if (user1Builder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              user1_ != protobuf.schema.UserOuterClass.User.getDefaultInstance()) {
            user1_ =
              protobuf.schema.UserOuterClass.User.newBuilder(user1_).mergeFrom(value).buildPartial();
          } else {
            user1_ = value;
          }
          onChanged();
        } else {
          user1Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.schema.User user1 = 4;</code>
       */
      public Builder clearUser1() {
        if (user1Builder_ == null) {
          user1_ = protobuf.schema.UserOuterClass.User.getDefaultInstance();
          onChanged();
        } else {
          user1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .protobuf.schema.User user1 = 4;</code>
       */
      public protobuf.schema.UserOuterClass.User.Builder getUser1Builder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getUser1FieldBuilder().getBuilder();
      }
      /**
       * <code>required .protobuf.schema.User user1 = 4;</code>
       */
      public protobuf.schema.UserOuterClass.UserOrBuilder getUser1OrBuilder() {
        if (user1Builder_ != null) {
          return user1Builder_.getMessageOrBuilder();
        } else {
          return user1_;
        }
      }
      /**
       * <code>required .protobuf.schema.User user1 = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protobuf.schema.UserOuterClass.User, protobuf.schema.UserOuterClass.User.Builder, protobuf.schema.UserOuterClass.UserOrBuilder> 
          getUser1FieldBuilder() {
        if (user1Builder_ == null) {
          user1Builder_ = new com.google.protobuf.SingleFieldBuilder<
              protobuf.schema.UserOuterClass.User, protobuf.schema.UserOuterClass.User.Builder, protobuf.schema.UserOuterClass.UserOrBuilder>(
                  getUser1(),
                  getParentForChildren(),
                  isClean());
          user1_ = null;
        }
        return user1Builder_;
      }

      private protobuf.schema.UserOuterClass.User user2_ = protobuf.schema.UserOuterClass.User.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protobuf.schema.UserOuterClass.User, protobuf.schema.UserOuterClass.User.Builder, protobuf.schema.UserOuterClass.UserOrBuilder> user2Builder_;
      /**
       * <code>required .protobuf.schema.User user2 = 8;</code>
       */
      public boolean hasUser2() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .protobuf.schema.User user2 = 8;</code>
       */
      public protobuf.schema.UserOuterClass.User getUser2() {
        if (user2Builder_ == null) {
          return user2_;
        } else {
          return user2Builder_.getMessage();
        }
      }
      /**
       * <code>required .protobuf.schema.User user2 = 8;</code>
       */
      public Builder setUser2(protobuf.schema.UserOuterClass.User value) {
        if (user2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user2_ = value;
          onChanged();
        } else {
          user2Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .protobuf.schema.User user2 = 8;</code>
       */
      public Builder setUser2(
          protobuf.schema.UserOuterClass.User.Builder builderForValue) {
        if (user2Builder_ == null) {
          user2_ = builderForValue.build();
          onChanged();
        } else {
          user2Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .protobuf.schema.User user2 = 8;</code>
       */
      public Builder mergeUser2(protobuf.schema.UserOuterClass.User value) {
        if (user2Builder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              user2_ != protobuf.schema.UserOuterClass.User.getDefaultInstance()) {
            user2_ =
              protobuf.schema.UserOuterClass.User.newBuilder(user2_).mergeFrom(value).buildPartial();
          } else {
            user2_ = value;
          }
          onChanged();
        } else {
          user2Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .protobuf.schema.User user2 = 8;</code>
       */
      public Builder clearUser2() {
        if (user2Builder_ == null) {
          user2_ = protobuf.schema.UserOuterClass.User.getDefaultInstance();
          onChanged();
        } else {
          user2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .protobuf.schema.User user2 = 8;</code>
       */
      public protobuf.schema.UserOuterClass.User.Builder getUser2Builder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getUser2FieldBuilder().getBuilder();
      }
      /**
       * <code>required .protobuf.schema.User user2 = 8;</code>
       */
      public protobuf.schema.UserOuterClass.UserOrBuilder getUser2OrBuilder() {
        if (user2Builder_ != null) {
          return user2Builder_.getMessageOrBuilder();
        } else {
          return user2_;
        }
      }
      /**
       * <code>required .protobuf.schema.User user2 = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protobuf.schema.UserOuterClass.User, protobuf.schema.UserOuterClass.User.Builder, protobuf.schema.UserOuterClass.UserOrBuilder> 
          getUser2FieldBuilder() {
        if (user2Builder_ == null) {
          user2Builder_ = new com.google.protobuf.SingleFieldBuilder<
              protobuf.schema.UserOuterClass.User, protobuf.schema.UserOuterClass.User.Builder, protobuf.schema.UserOuterClass.UserOrBuilder>(
                  getUser2(),
                  getParentForChildren(),
                  isClean());
          user2_ = null;
        }
        return user2Builder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.api.TestResponse)
    }

    static {
      defaultInstance = new TestResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.api.TestResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_api_TestResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_api_TestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016api/test.proto\022\014protobuf.api\032\021schema/u" +
      "ser.proto\"f\n\014TestResponse\022\n\n\002id\030\001 \002(\005\022$\n" +
      "\005user1\030\004 \002(\0132\025.protobuf.schema.User\022$\n\005u" +
      "ser2\030\010 \002(\0132\025.protobuf.schema.User"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protobuf.schema.UserOuterClass.getDescriptor(),
        }, assigner);
    internal_static_protobuf_api_TestResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_api_TestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_api_TestResponse_descriptor,
        new java.lang.String[] { "Id", "User1", "User2", });
    protobuf.schema.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
