// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/various_tag.proto

package protobuf.api;

public final class VariousTag {
  private VariousTag() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VariousTagRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.api.VariousTagRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string text = 1;</code>
     */
    boolean hasText();
    /**
     * <code>required string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code protobuf.api.VariousTagRequest}
   */
  public static final class VariousTagRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.api.VariousTagRequest)
      VariousTagRequestOrBuilder {
    // Use VariousTagRequest.newBuilder() to construct.
    private VariousTagRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VariousTagRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VariousTagRequest defaultInstance;
    public static VariousTagRequest getDefaultInstance() {
      return defaultInstance;
    }

    public VariousTagRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VariousTagRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              text_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.api.VariousTag.internal_static_protobuf_api_VariousTagRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.api.VariousTag.internal_static_protobuf_api_VariousTagRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.api.VariousTag.VariousTagRequest.class, protobuf.api.VariousTag.VariousTagRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<VariousTagRequest> PARSER =
        new com.google.protobuf.AbstractParser<VariousTagRequest>() {
      public VariousTagRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VariousTagRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VariousTagRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    /**
     * <code>required string text = 1;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.api.VariousTag.VariousTagRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.VariousTag.VariousTagRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.VariousTag.VariousTagRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.VariousTag.VariousTagRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.VariousTag.VariousTagRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.VariousTag.VariousTagRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.api.VariousTag.VariousTagRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.api.VariousTag.VariousTagRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.api.VariousTag.VariousTagRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.VariousTag.VariousTagRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.api.VariousTag.VariousTagRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.api.VariousTagRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.api.VariousTagRequest)
        protobuf.api.VariousTag.VariousTagRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.api.VariousTag.internal_static_protobuf_api_VariousTagRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.api.VariousTag.internal_static_protobuf_api_VariousTagRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.api.VariousTag.VariousTagRequest.class, protobuf.api.VariousTag.VariousTagRequest.Builder.class);
      }

      // Construct using protobuf.api.VariousTag.VariousTagRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.api.VariousTag.internal_static_protobuf_api_VariousTagRequest_descriptor;
      }

      public protobuf.api.VariousTag.VariousTagRequest getDefaultInstanceForType() {
        return protobuf.api.VariousTag.VariousTagRequest.getDefaultInstance();
      }

      public protobuf.api.VariousTag.VariousTagRequest build() {
        protobuf.api.VariousTag.VariousTagRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.api.VariousTag.VariousTagRequest buildPartial() {
        protobuf.api.VariousTag.VariousTagRequest result = new protobuf.api.VariousTag.VariousTagRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.api.VariousTag.VariousTagRequest) {
          return mergeFrom((protobuf.api.VariousTag.VariousTagRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.api.VariousTag.VariousTagRequest other) {
        if (other == protobuf.api.VariousTag.VariousTagRequest.getDefaultInstance()) return this;
        if (other.hasText()) {
          bitField0_ |= 0x00000001;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasText()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.api.VariousTag.VariousTagRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.api.VariousTag.VariousTagRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 1;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.api.VariousTagRequest)
    }

    static {
      defaultInstance = new VariousTagRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.api.VariousTagRequest)
  }

  public interface VariousTagResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.api.VariousTagResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 int32_1 = 1;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    boolean hasInt321();
    /**
     * <code>required int32 int32_1 = 1;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    int getInt321();

    /**
     * <code>required int32 int32_16 = 16;</code>
     */
    boolean hasInt3216();
    /**
     * <code>required int32 int32_16 = 16;</code>
     */
    int getInt3216();
  }
  /**
   * Protobuf type {@code protobuf.api.VariousTagResponse}
   */
  public static final class VariousTagResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.api.VariousTagResponse)
      VariousTagResponseOrBuilder {
    // Use VariousTagResponse.newBuilder() to construct.
    private VariousTagResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VariousTagResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VariousTagResponse defaultInstance;
    public static VariousTagResponse getDefaultInstance() {
      return defaultInstance;
    }

    public VariousTagResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VariousTagResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              int321_ = input.readInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00000002;
              int3216_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.api.VariousTag.internal_static_protobuf_api_VariousTagResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.api.VariousTag.internal_static_protobuf_api_VariousTagResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.api.VariousTag.VariousTagResponse.class, protobuf.api.VariousTag.VariousTagResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<VariousTagResponse> PARSER =
        new com.google.protobuf.AbstractParser<VariousTagResponse>() {
      public VariousTagResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VariousTagResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VariousTagResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INT32_1_FIELD_NUMBER = 1;
    private int int321_;
    /**
     * <code>required int32 int32_1 = 1;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public boolean hasInt321() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 int32_1 = 1;</code>
     *
     * <pre>
     * REQUIRED
     * </pre>
     */
    public int getInt321() {
      return int321_;
    }

    public static final int INT32_16_FIELD_NUMBER = 16;
    private int int3216_;
    /**
     * <code>required int32 int32_16 = 16;</code>
     */
    public boolean hasInt3216() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 int32_16 = 16;</code>
     */
    public int getInt3216() {
      return int3216_;
    }

    private void initFields() {
      int321_ = 0;
      int3216_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasInt321()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInt3216()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, int321_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(16, int3216_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, int321_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, int3216_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.api.VariousTag.VariousTagResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.VariousTag.VariousTagResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.VariousTag.VariousTagResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.VariousTag.VariousTagResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.VariousTag.VariousTagResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.VariousTag.VariousTagResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.api.VariousTag.VariousTagResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.api.VariousTag.VariousTagResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.api.VariousTag.VariousTagResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.VariousTag.VariousTagResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.api.VariousTag.VariousTagResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.api.VariousTagResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.api.VariousTagResponse)
        protobuf.api.VariousTag.VariousTagResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.api.VariousTag.internal_static_protobuf_api_VariousTagResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.api.VariousTag.internal_static_protobuf_api_VariousTagResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.api.VariousTag.VariousTagResponse.class, protobuf.api.VariousTag.VariousTagResponse.Builder.class);
      }

      // Construct using protobuf.api.VariousTag.VariousTagResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        int321_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        int3216_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.api.VariousTag.internal_static_protobuf_api_VariousTagResponse_descriptor;
      }

      public protobuf.api.VariousTag.VariousTagResponse getDefaultInstanceForType() {
        return protobuf.api.VariousTag.VariousTagResponse.getDefaultInstance();
      }

      public protobuf.api.VariousTag.VariousTagResponse build() {
        protobuf.api.VariousTag.VariousTagResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.api.VariousTag.VariousTagResponse buildPartial() {
        protobuf.api.VariousTag.VariousTagResponse result = new protobuf.api.VariousTag.VariousTagResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.int321_ = int321_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.int3216_ = int3216_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.api.VariousTag.VariousTagResponse) {
          return mergeFrom((protobuf.api.VariousTag.VariousTagResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.api.VariousTag.VariousTagResponse other) {
        if (other == protobuf.api.VariousTag.VariousTagResponse.getDefaultInstance()) return this;
        if (other.hasInt321()) {
          setInt321(other.getInt321());
        }
        if (other.hasInt3216()) {
          setInt3216(other.getInt3216());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInt321()) {
          
          return false;
        }
        if (!hasInt3216()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.api.VariousTag.VariousTagResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.api.VariousTag.VariousTagResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int int321_ ;
      /**
       * <code>required int32 int32_1 = 1;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public boolean hasInt321() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 int32_1 = 1;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public int getInt321() {
        return int321_;
      }
      /**
       * <code>required int32 int32_1 = 1;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder setInt321(int value) {
        bitField0_ |= 0x00000001;
        int321_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 int32_1 = 1;</code>
       *
       * <pre>
       * REQUIRED
       * </pre>
       */
      public Builder clearInt321() {
        bitField0_ = (bitField0_ & ~0x00000001);
        int321_ = 0;
        onChanged();
        return this;
      }

      private int int3216_ ;
      /**
       * <code>required int32 int32_16 = 16;</code>
       */
      public boolean hasInt3216() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 int32_16 = 16;</code>
       */
      public int getInt3216() {
        return int3216_;
      }
      /**
       * <code>required int32 int32_16 = 16;</code>
       */
      public Builder setInt3216(int value) {
        bitField0_ |= 0x00000002;
        int3216_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 int32_16 = 16;</code>
       */
      public Builder clearInt3216() {
        bitField0_ = (bitField0_ & ~0x00000002);
        int3216_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.api.VariousTagResponse)
    }

    static {
      defaultInstance = new VariousTagResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.api.VariousTagResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_api_VariousTagRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_api_VariousTagRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_api_VariousTagResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_api_VariousTagResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025api/various_tag.proto\022\014protobuf.api\"!\n" +
      "\021VariousTagRequest\022\014\n\004text\030\001 \002(\t\"7\n\022Vari" +
      "ousTagResponse\022\017\n\007int32_1\030\001 \002(\005\022\020\n\010int32" +
      "_16\030\020 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_api_VariousTagRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_api_VariousTagRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_api_VariousTagRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_protobuf_api_VariousTagResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_api_VariousTagResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_api_VariousTagResponse_descriptor,
        new java.lang.String[] { "Int321", "Int3216", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
